# Generated by Django 5.2.5 on 2025-08-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodigoQR',
            new_name='QR',
        ),
    ]
