# Generated by Django 5.2.5 on 2025-08-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_codigoqr_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
    ]
