# Generated by Django 5.2.5 on 2025-09-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_qr_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('Cédula de ciudadania', 'Cédula de ciudadania'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Cédula de extranjeria', 'Cédula de extranjeria')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Aprendiz', 'Aprendiz'), ('Instructor', 'Instructor'), ('Administrativo', 'Administrativo')], max_length=50),
        ),
    ]
