# Generated by Django 5.2.5 on 2025-09-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_user_groups_user_is_superuser_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='jornada',
            field=models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('mixto', 'Mixto')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='puntodecontrol',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qr',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ficha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='jornada',
            field=models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('mixto', 'Mixto')], max_length=50, null=True),
        ),
    ]
